/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Regenerate with: node scripts/generate-icon-map.mjs
 *
 * Why this file exists: `plugins/vuetify.ts` uses the `mdi-svg` icon set, which
 * treats an icon prop as raw SVG path data. A bare string like "mdiSend" would
 * therefore render `<path d="mdiSend">` — a blank icon and a console warning,
 * never an error. Mapping every name used to its real @mdi/js path is the only
 * way to make that failure impossible rather than merely unlikely.
 *
 * Importing the paths individually (rather than `import * as mdi`) keeps the
 * bundle tree-shaken: only the icons actually referenced ship.
 */

import { mdiAccessPoint, mdiAccountCheckOutline, mdiAccountCircle, mdiAccountGroupOutline,
   mdiAccountMultipleOutline, mdiAccountOffOutline, mdiAccountOutline, mdiAlertCircle,
   mdiAlertCircleOutline, mdiAlertOctagonOutline, mdiAlertOutline, mdiApi, mdiArrowDown,
   mdiArrowDownBold, mdiBrain, mdiCancel, mdiChartBoxOutline, mdiChatProcessingOutline,
   mdiCheck, mdiCheckCircle, mdiCheckCircleOutline, mdiChevronDown, mdiChevronLeft,
   mdiChevronRight, mdiChevronUp, mdiClockOutline, mdiClose, mdiCloseCircleOutline, mdiCodeJson,
   mdiCommentMultipleOutline, mdiContentCopy, mdiContentSaveOutline, mdiCubeOutline,
   mdiDatabaseOutline, mdiDebugStepOver, mdiDelete, mdiDeleteSweepOutline, mdiEye, mdiEyeOff,
   mdiFlaskOutline, mdiFormatLetterCase, mdiFormatListBulleted, mdiHelpCircleOutline,
   mdiHistory, mdiHomeOutline, mdiInboxArrowDownOutline, mdiInboxOutline, mdiInformationOutline,
   mdiKeyOutline, mdiLanConnect, mdiLanDisconnect, mdiLightningBoltOutline, mdiLinkVariant,
   mdiLoading, mdiLockReset, mdiLoginVariant, mdiLogout, mdiMagnify, mdiMagnifyClose,
   mdiMapSearchOutline, mdiMessageTextOutline, mdiMinusCircleOutline, mdiOpenInNew,
   mdiPauseCircleOutline, mdiPencil, mdiPencilOutline, mdiPlayCircleOutline, mdiPlus,
   mdiProgressClock, mdiQqchat, mdiRadar, mdiRefresh, mdiRestart, mdiRobotHappyOutline, mdiSend,
   mdiSendOutline, mdiSendVariantOutline, mdiServerOutline, mdiShieldAlertOutline,
   mdiShieldCheckOutline, mdiShieldKeyOutline, mdiSortClockDescendingOutline, mdiStarOutline,
   mdiStop, mdiSwapHorizontal, mdiTextBoxSearchOutline, mdiTimerSand, mdiTimerSandComplete,
   mdiToolboxOutline, mdiTuneVariant, mdiUndoVariant, mdiViewDashboardOutline, mdiWeatherNight,
   mdiWeatherSunny, mdiWrenchOutline, } from '@mdi/js';

/** 95 icons currently referenced by the WebUI. */
export const namiIconAliases: Record<string, string> = {
  mdiAccessPoint,
  mdiAccountCheckOutline,
  mdiAccountCircle,
  mdiAccountGroupOutline,
  mdiAccountMultipleOutline,
  mdiAccountOffOutline,
  mdiAccountOutline,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAlertOctagonOutline,
  mdiAlertOutline,
  mdiApi,
  mdiArrowDown,
  mdiArrowDownBold,
  mdiBrain,
  mdiCancel,
  mdiChartBoxOutline,
  mdiChatProcessingOutline,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircleOutline,
  mdiCodeJson,
  mdiCommentMultipleOutline,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiCubeOutline,
  mdiDatabaseOutline,
  mdiDebugStepOver,
  mdiDelete,
  mdiDeleteSweepOutline,
  mdiEye,
  mdiEyeOff,
  mdiFlaskOutline,
  mdiFormatLetterCase,
  mdiFormatListBulleted,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiHomeOutline,
  mdiInboxArrowDownOutline,
  mdiInboxOutline,
  mdiInformationOutline,
  mdiKeyOutline,
  mdiLanConnect,
  mdiLanDisconnect,
  mdiLightningBoltOutline,
  mdiLinkVariant,
  mdiLoading,
  mdiLockReset,
  mdiLoginVariant,
  mdiLogout,
  mdiMagnify,
  mdiMagnifyClose,
  mdiMapSearchOutline,
  mdiMessageTextOutline,
  mdiMinusCircleOutline,
  mdiOpenInNew,
  mdiPauseCircleOutline,
  mdiPencil,
  mdiPencilOutline,
  mdiPlayCircleOutline,
  mdiPlus,
  mdiProgressClock,
  mdiQqchat,
  mdiRadar,
  mdiRefresh,
  mdiRestart,
  mdiRobotHappyOutline,
  mdiSend,
  mdiSendOutline,
  mdiSendVariantOutline,
  mdiServerOutline,
  mdiShieldAlertOutline,
  mdiShieldCheckOutline,
  mdiShieldKeyOutline,
  mdiSortClockDescendingOutline,
  mdiStarOutline,
  mdiStop,
  mdiSwapHorizontal,
  mdiTextBoxSearchOutline,
  mdiTimerSand,
  mdiTimerSandComplete,
  mdiToolboxOutline,
  mdiTuneVariant,
  mdiUndoVariant,
  mdiViewDashboardOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWrenchOutline,
};
