/**
 * Vuetify instance and theme.
 *
 * Colours are defined here in JS rather than via a Sass settings file, so the
 * build needs no Sass toolchain. The palette is tuned for a dark, dense
 * operations console: a slate background, a single blue accent, and muted
 * surfaces that keep tables readable at high density.
 */

import { createVuetify } from 'vuetify';
import { aliases as vuetifyAliases, mdi } from 'vuetify/iconsets/mdi-svg';
import { namiIconAliases } from './icons.generated';

/**
 * Icon resolution.
 *
 * The `mdi-svg` set treats an icon prop as raw SVG path data, so a bare
 * `"mdiSend"` string renders `<path d="mdiSend">` — a blank icon, silently.
 * `namiIconAliases` maps every `mdi*` name the app uses to its real `@mdi/js`
 * path; it is generated by `scripts/generate-icon-map.mjs`.
 *
 * Vuetify's own aliases (`complete`, `cancel`, `close`, …) are merged in and
 * must not be dropped: built-in components depend on them for their internal
 * icons, which would otherwise go blank too.
 */
const aliases = {
  ...vuetifyAliases,
  ...namiIconAliases,
};

export const vuetify = createVuetify({
  icons: { defaultSet: 'mdi', aliases, sets: { mdi } },
  theme: {
    defaultTheme: 'namiDark',
    themes: {
      namiDark: {
        dark: true,
        colors: {
          background: '#0b0e14',
          surface: '#11151d',
          'surface-bright': '#1a212c',
          'surface-light': '#161b24',
          'surface-variant': '#232a36',
          'on-surface-variant': '#8b94a3',
          primary: '#4c9aff',
          'primary-darken-1': '#2f7fe0',
          secondary: '#7c8aa5',
          accent: '#5fb8ff',
          error: '#f87171',
          info: '#60a5fa',
          success: '#34d399',
          warning: '#fbbf24',
        },
        variables: {
          'border-color': '#232a36',
          'border-opacity': 1,
          'high-emphasis-opacity': 0.95,
          'medium-emphasis-opacity': 0.72,
          'disabled-opacity': 0.42,
        },
      },
      namiLight: {
        dark: false,
        colors: {
          background: '#f6f7f9',
          surface: '#ffffff',
          'surface-bright': '#ffffff',
          'surface-light': '#eef1f5',
          'surface-variant': '#e2e7ee',
          'on-surface-variant': '#5b6472',
          primary: '#1f6feb',
          'primary-darken-1': '#1a5fd0',
          secondary: '#5b6472',
          accent: '#0969da',
          error: '#cf222e',
          info: '#0969da',
          success: '#1a7f37',
          warning: '#9a6700',
        },
        variables: {
          'border-color': '#d8dee7',
          'border-opacity': 1,
        },
      },
    },
  },
  defaults: {
    VCard: { variant: 'flat', border: true, rounded: 'lg' },
    VTextField: { variant: 'outlined', density: 'comfortable', hideDetails: 'auto' },
    VSelect: { variant: 'outlined', density: 'comfortable', hideDetails: 'auto' },
    VTextarea: { variant: 'outlined', density: 'comfortable', hideDetails: 'auto' },
    VBtn: { variant: 'flat', rounded: 'lg' },
    VChip: { rounded: 'md', size: 'small' },
    VTable: { density: 'comfortable' },
    VDialog: { maxWidth: 720 },
    VSnackbar: { location: 'top right', timeout: 5000 },
  },
});
